before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
      - PACKAGE=github.com/padok-team/guacamole
    ldflags:
      - -X ${PACKAGE}/internal/version.Version=${VERSION}
      - -X ${PACKAGE}/internal/version.CommitHash=${COMMIT_HASH}
      - -X ${PACKAGE}/internal/version.BuildTimestamp=}${BUILD_TIMESTAMP}
    goos:
      - linux
    main: ./
    binary: guacamole
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*(feat:|feat\\/|feat(\\([^\\)]*\\)):).*"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*(fix:|fix\\/|fix(\\([^\\)]*\\)):).*"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^style"
      - "^refactor"
      - "^build"
      - "^ci"
      - "^chore(release)"

brews:
  # Post latest version
  - name: guacamole
    homepage: https://github.com/padok-team/guacamole
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: download_strategy
    repository:
      owner: padok-team
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_PAT }}"
  # Post tagged version because alternative_names configuration is only for goreleaser pro version
  - name: "{{ .Env.RELEASE_NAME }}"
    homepage: https://github.com/padok-team/guacamole
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: download_strategy
    repository:
      owner: padok-team
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_PAT }}"
