name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Get ldflags env values
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
          echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
          # Remove the v prefix from the version and the -rc<number> suffix from the release candidate version
          RELEASE_NAME=guacamole@${VERSION#v}
          echo "RELEASE_NAME=${RELEASE_NAME%-*}" >> $GITHUB_ENV

      - name: Check env variables
        run: |
          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP"
          echo "VERSION=$VERSION"
          echo "COMMIT_HASH=$COMMIT_HASH"
          echo "RELEASE_NAME=$RELEASE_NAME"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This token was created by cterence on 20/10/2023 to allow goreleaser to push to the homebrew tap
          # Read : https://goreleaser.com/errors/resource-not-accessible-by-integration/#learning-more
          HOMEBREW_PAT: ${{ secrets.HOMEBREW_PAT }}
